### ISSUE TITLE
Server minor version may change between packets

### ISSUE THREAD

**Issue by kevinboulain** [ansible/tacacs_plus#22] opened 2017-09-14 16:41 UTC
Hi there,

While testing this library with a [TACACS+](http://www.shrubbery.net/tac_plus/) server (`tacacs+` package from Debian's APT repository), I encountered a problem with connection reuse.

The following snippet will raise `socket.error` from the `authorize` method:
```python
import tacacs_plus.client, tacacs_plus.flags

c = tacacs_plus.client.TACACSClient('tacacs', 49, 'testing123')
c.authenticate('test', 'toto', authen_type=tacacs_plus.flags.TAC_PLUS_AUTHEN_TYPE_PAP)
c.authorize('test', authen_type=tacacs_plus.flags.TAC_PLUS_AUTHEN_TYPE_PAP)
```

It's not mandatory to specify `authen_type` in the `c.authorize` statement.

```
Traceback (most recent call last):
  File "example.py", line 5, in <module>
    c.authorize('test', authen_type=tacacs_plus.flags.TAC_PLUS_AUTHEN_TYPE_PAP)
  File ".../venv2/local/lib/python2.7/site-packages/tacacs_plus/client.py", line 242, in authorize
    TAC_PLUS_AUTHOR
  File ".../venv2/local/lib/python2.7/site-packages/tacacs_plus/client.py", line 136, in send
    raise socket.error
```

The problem goes away if I recreate a client.

Based on IETF's draft, it seems that the [minor version](https://tools.ietf.org/html/draft-grant-tacacs-02#page-5) may change for some commands if their implementation has changed [between the two minor version](https://tools.ietf.org/html/draft-grant-tacacs-02#page-37).

Looking at the code, the comparison fail on the version check: `resp_header.version` is `0xc0` and `header.version` is `0xc1`. Could the version check be relaxed to only verify the major component?

For the record, the `test` user is defined as follow in the `tac_plus.conf` configuration file:
```
user = test  {
  login = cleartext "toto"
  pap = cleartext "toto"
  service = exec {
    priv-lvl = 15
  }
}
```

Regards.

**Comment by crisidev** [comment] 2018-01-26 10:12
IMHO a relaxed protocol version check is ok, since it will fix the client reuse issue that I have also experienced. @ryanpetrello thoughts? I can work on a patch for this if you are ok with the general idea.

**Comment by ryanpetrello** [comment] 2018-01-26 18:00
@crisidev yep, that sounds reasonable to me

**Comment by crisidev** [comment] 2018-01-26 18:04
Ok, I am gonna work on it. I cannot test the PAP authentication where this issue is coming from since I don't have the infrastructure. I cannot reproduce the issue using ascii authentication scheme.
But as @ether42 says, the RFC is telling us the minor version can change.

@ether42 are you able to test the change if I make a pull request?

**Comment by crisidev** [comment] 2018-01-29 14:40
@ether42 I created a new branch with a possible fix for this issue: https://github.com/ansible/tacacs_plus/tree/relaxed_version_check

Do you mind to test it. I will merge it to master if the fix works for you.

**Comment by kevinboulain** [comment] 2018-02-01 14:12
@crisidev just tested it, unfortunately it doesn't work.
The problem, as highlighted by the traceback, is in the following condition (from `client.py`):
```python
            if any([
                resp_header.version != header.version,
                resp_header.type != header.type,
                resp_header.session_id != header.session_id
            ]):
```
For the first packet I get `resp_header.version = 193` and `header.version = 193`.
For the second packet, I get `resp_header.version = 192` and `header.version = 193`.

**Comment by Michael9127** [comment] 2018-08-10 18:57
According to section 4.4.1 of the RFC (https://tools.ietf.org/html/draft-ietf-opsawg-tacacs-10), the minor version doesnt effect authorization: 
>The changes between minor_version 0 and 1 apply only to the authentication process". 

>All authorisation and accounting and ASCII authentication use minor_version number of 0."

I think the check on this line should only compare major versions.
https://github.com/ansible/tacacs_plus/blob/9ba553f79efcc7b955001503d1953900ba6284a4/tacacs_plus/client.py#L131

**Closed as completed** 2018-08-10 19:40 UTC

**Comment by cmctague** [comment] 2019-05-09 14:30
Based on the line quoted from the TACACS+ I-D above:

>  All authorisation and accounting and ASCII authentication use minor_version number of 0.

The client should never be sending a version of 193 (0xC1) to begin with, except for authentication of non-ASCII types.  The source change that will take care of this is to force the header version in TACACSClient.authorize() and TACACSClient.account() before calling self.send().

`self.version_min = TAC_PLUS_MINOR_VER`

This effectively undoes the setting of the self.version_min in TACACSClient.authenticate() which takes place for non-ascii auth types.

Making the comparison of the reply version less rigorous only helps, if the server actually tolerates the client sending the wrong version, which at least tac_plus does not.
